# Generated by Django 3.2.3 on 2022-02-09 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220209_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 15, 8, 43, 128979), verbose_name='Commented on'),
        ),
    ]
