# Generated by Django 3.2.3 on 2022-02-09 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_comment_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 18, 37, 45, 380033), verbose_name='Commented on'),
        ),
    ]
