# Generated by Django 3.2.3 on 2022-02-10 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_comment_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 19, 42, 23, 92147), verbose_name='Commented on'),
        ),
    ]
