# Generated by Django 3.2.3 on 2022-03-02 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20220302_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 2, 15, 26, 10, 217683), verbose_name='Commented on'),
        ),
    ]
