# Generated by Django 3.2.3 on 2022-03-08 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_comment_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 16, 59, 30, 100128), verbose_name='Commented on'),
        ),
    ]
