# Generated by Django 3.2.3 on 2022-03-08 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_comment_comment_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='postQus',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 17, 51, 31, 544061), verbose_name='Commented on'),
        ),
    ]
