# Generated by Django 3.2.3 on 2022-03-09 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20220308_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 19, 47, 29, 435020), verbose_name='Commented on'),
        ),
        migrations.AlterField(
            model_name='postqus',
            name='post_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
