# Generated by Django 3.2.3 on 2022-03-09 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20220308_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 23, 32, 14, 239243), verbose_name='Commented on'),
        ),
        migrations.AlterField(
            model_name='postqus',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
