# Generated by Django 3.2.3 on 2022-03-09 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_comment_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postqus',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 18, 14, 13, 998136), verbose_name='Commented on'),
        ),
    ]
