# Generated by Django 3.2.3 on 2022-03-10 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20220309_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 19, 52, 59, 702470), verbose_name='Commented on'),
        ),
    ]
