# Generated by Django 3.2.3 on 2022-03-10 06:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_comment_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_by',
            field=models.ForeignKey(default='man123', on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 1, 48, 54, 346148), verbose_name='Commented on'),
        ),
        migrations.AlterField(
            model_name='postqus',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
