# Generated by Django 3.2.3 on 2022-03-10 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20220310_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 1, 50, 1, 859838), verbose_name='Commented on'),
        ),
    ]
