# Generated by Django 3.2.3 on 2022-03-10 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_comment_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 1, 56, 23, 33067), verbose_name='Commented on'),
        ),
    ]
