# Generated by Django 3.2.3 on 2022-03-30 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20220330_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=1122, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 19, 43, 51, 274778), verbose_name='Commented on'),
        ),
    ]
