# Generated by Django 4.0.2 on 2022-04-03 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20220330_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 20, 14, 14, 538217), verbose_name='Commented on'),
        ),
    ]
