# Generated by Django 4.0.2 on 2022-04-21 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_alter_comment_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 13, 19, 11, 475129), verbose_name='Commented on'),
        ),
    ]
